server:
    servlet:
        context-path: /expenseapi
    port: 8081
spring:
    application:
        name: expenseapi
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
#        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
            path: /h2-console
            web-allow-others: false